server:
  port: 9099
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server
  elasticsearch:
    uris: http://localhost:9200

myapplication:
  user-service:
    feign-client: http://localhost:9096/api/v1

# JWT
myjwt:
  secretkey: ${secretKey}
  audience: ${audience}
  issuer: ${issuer}