apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodbdeployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
            limits:
              memory: 256Mi
              cpu: 250m
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "AdminBilge"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "m=YEJ-Sw_2oF6lp8uPr5"