server:
  port: 9088

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java3auth
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true




# JWT
myjwt:
  secretKey: ${secretKey}
  audience: ${audience}
  issuer: ${issuer}