server:
  port: 9096

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.173.108.167:1111/java3user
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# JWT
myjwt:
  secretkey: ${secretKey}
  audience: ${audience}
  issuer: ${issuer}